runtime: nodejs16

env_variables:
  DB_HOST: ""
  DB_USER: ""
  DB_PASSWORD: ""
  DB_DATABASE: ""
  JWT_SECRET: ""

automatic_scaling:
  target_cpu_utilization: 0.65
  target_throughput_utilization: 0.65
